<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="VICTOR-PC"><DocLocation><![CDATA[C:\Unified Functional Testing\4.0\1117-HMC-H5-比价-模块化]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[1117-HMC-H5-比价-模块化]]></DName>
<Res><![CDATA[Res4]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[00-MainAction]]></AName>
<Action rID="T5">
<AName><![CDATA[01-HomeAction]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:06]]></Time>
<TimeTick>1479898986</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "chrome.exe",1]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:06]]></Time>
<TimeTick>1479898986</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" Source="01-HomeAction" SourceLine="5" >
<Disp><![CDATA[Run "chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="01-HomeAction" SourceLine="5" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:10]]></Time>
<TimeTick>1479898990</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[好买车-首页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:10]]></Time>
<TimeTick>1479898990</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[好买车-首页.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:10]]></Time>
<TimeTick>1479898990</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" Source="01-HomeAction" SourceLine="8" >
<Disp><![CDATA[好买车-首页.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[选择车型按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:11]]></Time>
<TimeTick>1479898991</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" Source="01-HomeAction" SourceLine="10" >
<Disp><![CDATA[选择车型按钮.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="16" Source="01-HomeAction" SourceLine="8" >
<Disp><![CDATA[好买车-首页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" Source="01-HomeAction" SourceLine="8" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/23 - 19:03:06" eTime="2016/11/23 - 19:03:11" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Passed" >
<Disp><![CDATA[01-HomeAction Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T12">
<AName><![CDATA[02-CarBrand-Landrover]]></AName>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:13]]></Time>
<TimeTick>1479898993</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[好买车-首页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:13]]></Time>
<TimeTick>1479898993</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[路虎图标.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:13]]></Time>
<TimeTick>1479898993</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="27" Source="02-CarBrand-Landrover" SourceLine="3" >
<Disp><![CDATA[路虎图标.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[揽胜.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:14]]></Time>
<TimeTick>1479898994</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="30" Source="02-CarBrand-Landrover" SourceLine="5" >
<Disp><![CDATA[揽胜.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="26" Source="02-CarBrand-Landrover" SourceLine="3" >
<Disp><![CDATA[好买车-首页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="25" Source="02-CarBrand-Landrover" SourceLine="3" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/23 - 19:03:12" eTime="2016/11/23 - 19:03:14" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="22" >
<Disp><![CDATA[02-CarBrand-Landrover Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T17">
<AName><![CDATA[03-Trad-Step1]]></AName>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:15]]></Time>
<TimeTick>1479898995</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:15]]></Time>
<TimeTick>1479898995</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[车型详情页.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:15]]></Time>
<TimeTick>1479898995</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="37" Source="03-Trad-Step1" SourceLine="3" >
<Disp><![CDATA[车型详情页.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[去比价按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:17]]></Time>
<TimeTick>1479898997</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="40" Source="03-Trad-Step1" SourceLine="5" >
<Disp><![CDATA[去比价按钮.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[第一步和最后一步的下一步.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:18]]></Time>
<TimeTick>1479898998</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="43" Source="03-Trad-Step1" SourceLine="7" >
<Disp><![CDATA[第一步和最后一步的下一步.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="36" Source="03-Trad-Step1" SourceLine="3" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="35" Source="03-Trad-Step1" SourceLine="3" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/23 - 19:03:14" eTime="2016/11/23 - 19:03:18" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="32" >
<Disp><![CDATA[03-Trad-Step1 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T23">
<AName><![CDATA[04-CarModel-Landrover]]></AName>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:19]]></Time>
<TimeTick>1479898999</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:19]]></Time>
<TimeTick>1479898999</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[第二步款型选择.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:19]]></Time>
<TimeTick>1479898999</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="50" Source="04-CarModel-Landrover" SourceLine="3" >
<Disp><![CDATA[第二步款型选择.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="49" Source="04-CarModel-Landrover" SourceLine="3" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="48" Source="04-CarModel-Landrover" SourceLine="3" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/23 - 19:03:18" eTime="2016/11/23 - 19:03:20" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="45" >
<Disp><![CDATA[04-CarModel-Landrover Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T27">
<AName><![CDATA[05-CarColor-Landrover]]></AName>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:21]]></Time>
<TimeTick>1479899001</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:21]]></Time>
<TimeTick>1479899001</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[阿鲁巴灰银.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:21]]></Time>
<TimeTick>1479899001</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="57" Source="05-CarColor-Landrover" SourceLine="2" >
<Disp><![CDATA[阿鲁巴灰银.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="56" Source="05-CarColor-Landrover" SourceLine="2" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="55" Source="05-CarColor-Landrover" SourceLine="2" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/23 - 19:03:20" eTime="2016/11/23 - 19:03:22" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="52" >
<Disp><![CDATA[05-CarColor-Landrover Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T31">
<AName><![CDATA[06-License-huA]]></AName>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:22]]></Time>
<TimeTick>1479899002</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:22]]></Time>
<TimeTick>1479899002</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[牌照选择-上沪牌.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:22]]></Time>
<TimeTick>1479899002</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="64" Source="06-License-huA" SourceLine="2" >
<Disp><![CDATA[牌照选择-上沪牌.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="63" Source="06-License-huA" SourceLine="2" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="62" Source="06-License-huA" SourceLine="2" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/23 - 19:03:22" eTime="2016/11/23 - 19:03:23" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="59" >
<Disp><![CDATA[06-License-huA Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T35">
<AName><![CDATA[07-PayModel-AllPay]]></AName>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:24]]></Time>
<TimeTick>1479899004</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:24]]></Time>
<TimeTick>1479899004</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[购车方式-全款购车.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:24]]></Time>
<TimeTick>1479899004</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="71" Source="07-PayModel-AllPay" SourceLine="2" >
<Disp><![CDATA[购车方式-全款购车.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="70" Source="07-PayModel-AllPay" SourceLine="2" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="69" Source="07-PayModel-AllPay" SourceLine="2" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/23 - 19:03:23" eTime="2016/11/23 - 19:03:25" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="66" >
<Disp><![CDATA[07-PayModel-AllPay Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T39">
<AName><![CDATA[08-PurchaseTime-m3Month]]></AName>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:25]]></Time>
<TimeTick>1479899005</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:25]]></Time>
<TimeTick>1479899005</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[购车时间-3个月以后.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:25]]></Time>
<TimeTick>1479899005</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="78" Source="08-PurchaseTime-m3Month" SourceLine="2" >
<Disp><![CDATA[购车时间-3个月以后.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="77" Source="08-PurchaseTime-m3Month" SourceLine="2" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="76" Source="08-PurchaseTime-m3Month" SourceLine="2" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/23 - 19:03:25" eTime="2016/11/23 - 19:03:26" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="73" >
<Disp><![CDATA[08-PurchaseTime-m3Month Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T43">
<AName><![CDATA[09-Area]]></AName>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:26]]></Time>
<TimeTick>1479899006</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:26]]></Time>
<TimeTick>1479899006</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[区域-浦东.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:26]]></Time>
<TimeTick>1479899006</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="85" Source="09-Area" SourceLine="2" >
<Disp><![CDATA[区域-浦东.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[商圈-金桥.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:28]]></Time>
<TimeTick>1479899008</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="88" Source="09-Area" SourceLine="4" >
<Disp><![CDATA[商圈-金桥.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="84" Source="09-Area" SourceLine="2" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="83" Source="09-Area" SourceLine="2" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/23 - 19:03:26" eTime="2016/11/23 - 19:03:29" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="80" >
<Disp><![CDATA[09-Area Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T48">
<AName><![CDATA[10-Trad-Step9]]></AName>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:30]]></Time>
<TimeTick>1479899010</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:30]]></Time>
<TimeTick>1479899010</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[第一步和最后一步的下一步.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:30]]></Time>
<TimeTick>1479899010</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="95" Source="10-Trad-Step9" SourceLine="3" >
<Disp><![CDATA[第一步和最后一步的下一步.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="94" Source="10-Trad-Step9" SourceLine="3" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="93" Source="10-Trad-Step9" SourceLine="3" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/23 - 19:03:29" eTime="2016/11/23 - 19:03:30" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="90" >
<Disp><![CDATA[10-Trad-Step9 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T52">
<AName><![CDATA[11-RegisterLogin]]></AName>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:31]]></Time>
<TimeTick>1479899011</TimeTick>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:31]]></Time>
<TimeTick>1479899011</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[用户手机号码.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:31]]></Time>
<TimeTick>1479899011</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="102" Source="11-RegisterLogin" SourceLine="3" >
<Disp><![CDATA[用户手机号码.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA["老用户提示语"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:54]]></Time>
<TimeTick>1479899034</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="140" status="Warning" Source="11-RegisterLogin" SourceLine="24" >
<Disp><![CDATA["老用户提示语"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA["老用户提示语"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=WebElement<br>innertext=欢迎回来，尊敬的好买车用户！<br>html tag=DIV<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (168 objects found)&nbsp;</FONT></u><br>
micclass=WebElement<br>html tag=DIV<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
html id=<SPAN class=passed> (Used</SPAN>, 162 matches)</SPAN><br>class=attention_msg<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>innertext=欢迎回来，尊敬的好买车用户！<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:54]]></Time>
<TimeTick>1479899034</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="141" Source="11-RegisterLogin" SourceLine="24" >
<Disp><![CDATA["老用户提示语"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[免费验证码.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:55]]></Time>
<TimeTick>1479899035</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="144" Source="11-RegisterLogin" SourceLine="42" >
<Disp><![CDATA[免费验证码.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="101" status="Warning" Source="11-RegisterLogin" SourceLine="3" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="100" status="Warning" Source="11-RegisterLogin" SourceLine="3" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Action rID="T59">
<AName><![CDATA[12-AdminLogin]]></AName>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:57]]></Time>
<TimeTick>1479899037</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:57]]></Time>
<TimeTick>1479899037</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="149" status="Passed" Source="12-AdminLogin" SourceLine="3" >
<Disp><![CDATA[Run "IExplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="148" status="Passed" Source="12-AdminLogin" SourceLine="3" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:58]]></Time>
<TimeTick>1479899038</TimeTick>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA["管理后台系统界面"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (2 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=管理后台系统界面<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>title=管理后台系统界面<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>openurl=res://ieframe.dll/securityatrisk.htm<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=安全设置风险<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hasstatusbar=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hasmenubar=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hastoolbar=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:58]]></Time>
<TimeTick>1479899038</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="152" Source="12-AdminLogin" SourceLine="5" >
<Disp><![CDATA["管理后台系统界面"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:58]]></Time>
<TimeTick>1479899038</TimeTick>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:03:58]]></Time>
<TimeTick>1479899038</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="155" Source="12-AdminLogin" SourceLine="5" >
<Disp><![CDATA[管理后台系统界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[用户名输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[2016/11/23 - 19:04:01]]></Time>
<TimeTick>1479899041</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="158" Source="12-AdminLogin" SourceLine="7" >
<Disp><![CDATA[用户名输入框.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[密码按钮.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Hmc1234"]]></Details>
<Time><![CDATA[2016/11/23 - 19:04:01]]></Time>
<TimeTick>1479899041</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="161" Source="12-AdminLogin" SourceLine="8" >
<Disp><![CDATA[密码按钮.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[登录按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/23 - 19:04:01]]></Time>
<TimeTick>1479899041</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="164" Source="12-AdminLogin" SourceLine="9" >
<Disp><![CDATA[登录按钮.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="154" Source="12-AdminLogin" SourceLine="5" >
<Disp><![CDATA[管理后台系统界面]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="151" Source="12-AdminLogin" SourceLine="5" >
<Disp><![CDATA[管理后台系统界面]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/23 - 19:03:56" eTime="2016/11/23 - 19:04:01" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="145" status="Passed" >
<Disp><![CDATA[12-AdminLogin Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T69">
<AName><![CDATA[13-VerifyCode]]></AName>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/23 - 19:04:03]]></Time>
<TimeTick>1479899043</TimeTick>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA["管理后台系统界面"- Smart Identification]]></Obj>