<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="VICTOR-PC"><DocLocation><![CDATA[C:\Unified Functional Testing\4.0\1116-HMC-PC-报价-模块化]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[1116-HMC-PC-报价-模块化]]></DName>
<Res><![CDATA[Res13]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[00MainAction]]></AName>
<Action rID="T5">
<AName><![CDATA[01AdminLogin]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/11/24 - 14:35:59]]></Time>
<TimeTick>1479969359</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Details>
<Time><![CDATA[2016/11/24 - 14:35:59]]></Time>
<TimeTick>1479969359</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" Source="01AdminLogin" SourceLine="2" >
<Disp><![CDATA[Run "IExplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="01AdminLogin" SourceLine="2" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:01]]></Time>
<TimeTick>1479969361</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:01]]></Time>
<TimeTick>1479969361</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:01]]></Time>
<TimeTick>1479969361</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" Source="01AdminLogin" SourceLine="4" >
<Disp><![CDATA[管理后台系统界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[用户名输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:04]]></Time>
<TimeTick>1479969364</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" Source="01AdminLogin" SourceLine="6" >
<Disp><![CDATA[用户名输入框.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[密码输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Hmc1234"]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:04]]></Time>
<TimeTick>1479969364</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" Source="01AdminLogin" SourceLine="7" >
<Disp><![CDATA[密码输入框.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[登录按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:04]]></Time>
<TimeTick>1479969364</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="26" Source="01AdminLogin" SourceLine="8" >
<Disp><![CDATA[登录按钮.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="16" Source="01AdminLogin" SourceLine="4" >
<Disp><![CDATA[管理后台系统界面]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" Source="01AdminLogin" SourceLine="4" >
<Disp><![CDATA[管理后台系统界面]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/24 - 14:35:59" eTime="2016/11/24 - 14:36:05" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Passed" >
<Disp><![CDATA[01AdminLogin Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T14">
<AName><![CDATA[02AdminOperation]]></AName>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[系统主界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:07]]></Time>
<TimeTick>1479969367</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[系统主界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:07]]></Time>
<TimeTick>1479969367</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[系统主界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:07]]></Time>
<TimeTick>1479969367</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="33" Source="02AdminOperation" SourceLine="2" >
<Disp><![CDATA[系统主界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[订单管理-菜单.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:07]]></Time>
<TimeTick>1479969367</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="36" Source="02AdminOperation" SourceLine="3" >
<Disp><![CDATA[订单管理-菜单.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA["待报报价单-订单管理"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:29]]></Time>
<TimeTick>1479969389</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="75" status="Warning" Source="02AdminOperation" SourceLine="5" >
<Disp><![CDATA["待报报价单-订单管理"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA["待报报价单-订单管理"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=待报报价单(21)<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (90 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
text=待报报价单(21)<SPAN class=Failed> (Skipped)</SPAN><br>html id=<SPAN class=passed> (Used</SPAN>, 88 matches)</SPAN><br>class=<SPAN class=passed> (Used</SPAN>, 68 matches)</SPAN><br>name=待报报价单(21)<SPAN class=Failed> (Skipped)</SPAN><br>href=http://oms-test.haomaiche.com/admin/web/webRespond.jsp?param=1<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:29]]></Time>
<TimeTick>1479969389</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="76" Source="02AdminOperation" SourceLine="5" >
<Disp><![CDATA["待报报价单-订单管理"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[待报报价单-订单管理.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:29]]></Time>
<TimeTick>1479969389</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="77" Source="02AdminOperation" SourceLine="5" >
<Disp><![CDATA[待报报价单-订单管理.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[待报价信息框架]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:34]]></Time>
<TimeTick>1479969394</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:34]]></Time>
<TimeTick>1479969394</TimeTick>
<NodeArgs eType="General" icon="14" nRep="80" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:34]]></Time>
<TimeTick>1479969394</TimeTick>
<NodeArgs eType="General" icon="14" nRep="81" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:34]]></Time>
<TimeTick>1479969394</TimeTick>
<NodeArgs eType="General" icon="14" nRep="82" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:34]]></Time>
<TimeTick>1479969394</TimeTick>
<NodeArgs eType="General" icon="14" nRep="83" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:34]]></Time>
<TimeTick>1479969394</TimeTick>
<NodeArgs eType="General" icon="14" nRep="84" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ 捷豹路虎江杨南路店 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:34]]></Time>
<TimeTick>1479969394</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="86" Source="02AdminOperation" SourceLine="40" >
<Disp><![CDATA[[ 捷豹路虎江杨南路店 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA["4S店人员信息":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:43]]></Time>
<TimeTick>1479969403</TimeTick>
<NodeArgs eType="General" icon="14" nRep="88" >
<Disp><![CDATA["4S店人员信息":Function Call]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="79" Source="02AdminOperation" SourceLine="17" >
<Disp><![CDATA[待报价信息框架]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="32" status="Warning" Source="02AdminOperation" SourceLine="2" >
<Disp><![CDATA[系统主界面]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="31" status="Warning" Source="02AdminOperation" SourceLine="2" >
<Disp><![CDATA[系统主界面]]></Disp>
</NodeArgs>
</Step>
<Action rID="T30">
<AName><![CDATA[03Merchant]]></AName>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:50]]></Time>
<TimeTick>1479969410</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:50]]></Time>
<TimeTick>1479969410</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="93" status="Passed" Source="03Merchant" SourceLine="5" >
<Disp><![CDATA[Run "IExplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="92" status="Passed" Source="03Merchant" SourceLine="5" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[4S店后台管理系统登录界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:52]]></Time>
<TimeTick>1479969412</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[4S店后台管理系统登录界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:52]]></Time>
<TimeTick>1479969412</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="96" Source="03Merchant" SourceLine="7" >
<Disp><![CDATA[4S店后台管理系统登录界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[登录界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:52]]></Time>
<TimeTick>1479969412</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[用户名输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["XSHXJJBLH002"]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:52]]></Time>
<TimeTick>1479969412</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="100" Source="03Merchant" SourceLine="9" >
<Disp><![CDATA[用户名输入框.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[密码输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["123456"]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:52]]></Time>
<TimeTick>1479969412</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="103" Source="03Merchant" SourceLine="10" >
<Disp><![CDATA[密码输入框.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[登录按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:53]]></Time>
<TimeTick>1479969413</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="106" Source="03Merchant" SourceLine="12" >
<Disp><![CDATA[登录按钮.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="99" Source="03Merchant" SourceLine="9" >
<Disp><![CDATA[登录界面]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[商户端操作界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:54]]></Time>
<TimeTick>1479969414</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[商户端操作界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:54]]></Time>
<TimeTick>1479969414</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="110" Source="03Merchant" SourceLine="14" >
<Disp><![CDATA[商户端操作界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[请报价-菜单.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:55]]></Time>
<TimeTick>1479969415</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="113" Source="03Merchant" SourceLine="16" >
<Disp><![CDATA[请报价-菜单.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[待报价列表框架]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:59]]></Time>
<TimeTick>1479969419</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA["待报价单列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:59]]></Time>
<TimeTick>1479969419</TimeTick>
<NodeArgs eType="General" icon="14" nRep="116" >
<Disp><![CDATA["待报价单列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA["待报价单列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:59]]></Time>
<TimeTick>1479969419</TimeTick>
<NodeArgs eType="General" icon="14" nRep="117" >
<Disp><![CDATA["待报价单列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ 去报价 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 14:36:59]]></Time>
<TimeTick>1479969419</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="119" Source="03Merchant" SourceLine="26" >
<Disp><![CDATA[[ 去报价 ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="115" Source="03Merchant" SourceLine="23" >
<Disp><![CDATA[待报价列表框架]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[去报价详情框架]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:00]]></Time>
<TimeTick>1479969420</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[车源单选按钮.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#2"]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:00]]></Time>
<TimeTick>1479969420</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="123" Source="03Merchant" SourceLine="35" >
<Disp><![CDATA[车源单选按钮.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[优惠比例.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["6.7"]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:00]]></Time>
<TimeTick>1479969420</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="126" Source="03Merchant" SourceLine="56" >
<Disp><![CDATA[优惠比例.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA["保险税费表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:00]]></Time>
<TimeTick>1479969420</TimeTick>
<NodeArgs eType="General" icon="14" nRep="128" >
<Disp><![CDATA["保险税费表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA["免费询价-右侧简图":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:01]]></Time>
<TimeTick>1479969421</TimeTick>
<NodeArgs eType="General" icon="14" nRep="130" >
<Disp><![CDATA["免费询价-右侧简图":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[综合服务费.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["3000"]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:02]]></Time>
<TimeTick>1479969422</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="133" Source="03Merchant" SourceLine="78" >
<Disp><![CDATA[综合服务费.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA["是否可自主回原籍单选框"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:24]]></Time>
<TimeTick>1479969444</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="173" status="Warning" Source="03Merchant" SourceLine="95" >
<Disp><![CDATA["是否可自主回原籍单选框"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA["是否可自主回原籍单选框"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>visible=-1<br>name=licence<br>micclass=WebRadioGroup<br>html tag=INPUT<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (3 objects found)&nbsp;</FONT></u><br>
micclass=WebRadioGroup<br>html tag=INPUT<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=licence<SPAN class=Failed> (Skipped)</SPAN><br>html id=lrd3<SPAN class=Failed> (Skipped)</SPAN><br>class=<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>items count=2<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:24]]></Time>
<TimeTick>1479969444</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="174" Source="03Merchant" SourceLine="95" >
<Disp><![CDATA["是否可自主回原籍单选框"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[推荐可上外牌.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:24]]></Time>
<TimeTick>1479969444</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="177" Source="03Merchant" SourceLine="104" >
<Disp><![CDATA[推荐可上外牌.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[牌照费用.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1500"]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:24]]></Time>
<TimeTick>1479969444</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="180" Source="03Merchant" SourceLine="136" >
<Disp><![CDATA[牌照费用.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[贷款补贴.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["3000"]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:26]]></Time>
<TimeTick>1479969446</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="184" Source="03Merchant" SourceLine="153" >
<Disp><![CDATA[贷款补贴.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[贷款手续费.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["300"]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:27]]></Time>
<TimeTick>1479969447</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="187" Source="03Merchant" SourceLine="155" >
<Disp><![CDATA[贷款手续费.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[置换补贴.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:31]]></Time>
<TimeTick>1479969451</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="212" Source="03Merchant" SourceLine="169" >
<Disp><![CDATA[置换补贴.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[颜色加价.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["700"]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:32]]></Time>
<TimeTick>1479969452</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="215" Source="03Merchant" SourceLine="175" >
<Disp><![CDATA[颜色加价.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[现金加价.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["900"]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:34]]></Time>
<TimeTick>1479969454</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="218" Source="03Merchant" SourceLine="177" >
<Disp><![CDATA[现金加价.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[提交询价单.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:35]]></Time>
<TimeTick>1479969455</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="221" Source="03Merchant" SourceLine="192" >
<Disp><![CDATA[提交询价单.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA["弹出框内容表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:36]]></Time>
<TimeTick>1479969456</TimeTick>
<NodeArgs eType="General" icon="14" nRep="223" >
<Disp><![CDATA["弹出框内容表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA["弹出框内容表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:36]]></Time>
<TimeTick>1479969456</TimeTick>
<NodeArgs eType="General" icon="14" nRep="224" >
<Disp><![CDATA["弹出框内容表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA["弹出框内容表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:36]]></Time>
<TimeTick>1479969456</TimeTick>
<NodeArgs eType="General" icon="14" nRep="225" >
<Disp><![CDATA["弹出框内容表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA["弹出框内容表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:36]]></Time>
<TimeTick>1479969456</TimeTick>
<NodeArgs eType="General" icon="14" nRep="226" >
<Disp><![CDATA["弹出框内容表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA["弹出框内容表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:36]]></Time>
<TimeTick>1479969456</TimeTick>
<NodeArgs eType="General" icon="14" nRep="227" >
<Disp><![CDATA["弹出框内容表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA["弹出框内容表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:36]]></Time>
<TimeTick>1479969456</TimeTick>
<NodeArgs eType="General" icon="14" nRep="228" >
<Disp><![CDATA["弹出框内容表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA["弹出框内容表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:36]]></Time>
<TimeTick>1479969456</TimeTick>
<NodeArgs eType="General" icon="14" nRep="229" >
<Disp><![CDATA["弹出框内容表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[确认提交-最后的弹出框.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:38]]></Time>
<TimeTick>1479969458</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="232" Source="03Merchant" SourceLine="221" >
<Disp><![CDATA[确认提交-最后的弹出框.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="122" status="Warning" Source="03Merchant" SourceLine="35" >
<Disp><![CDATA[去报价详情框架]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="109" status="Warning" Source="03Merchant" SourceLine="14" >
<Disp><![CDATA[商户端操作界面]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[windows弹出框]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:39]]></Time>
<TimeTick>1479969459</TimeTick>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[确定.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 14:37:39]]></Time>
<TimeTick>1479969459</TimeTick>