<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="VICTOR-PC"><DocLocation><![CDATA[C:\Unified Functional Testing\4.0\1114-HMC-H5-比价]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[1114-HMC-H5-比价]]></DName>
<Res><![CDATA[Res3]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[H5Operation]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:13]]></Time>
<TimeTick>1479112033</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "chrome.exe",1]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:13]]></Time>
<TimeTick>1479112033</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="H5Operation" SourceLine="5" >
<Disp><![CDATA[Run "chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="H5Operation" SourceLine="5" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:17]]></Time>
<TimeTick>1479112037</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[好买车-首页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:17]]></Time>
<TimeTick>1479112037</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[好买车-首页.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:17]]></Time>
<TimeTick>1479112037</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" Source="H5Operation" SourceLine="8" >
<Disp><![CDATA[好买车-首页.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[选择车型按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:18]]></Time>
<TimeTick>1479112038</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" Source="H5Operation" SourceLine="10" >
<Disp><![CDATA[选择车型按钮.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[马自达8图标.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:19]]></Time>
<TimeTick>1479112039</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" Source="H5Operation" SourceLine="12" >
<Disp><![CDATA[马自达8图标.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA["马自达款型"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (24 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Image<br>image type=Image Link<br>html tag=IMG<br>alt=<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (71 objects found)&nbsp;</FONT></u><br>
micclass=Image<br>html tag=IMG<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
alt=<SPAN class=passed> (Used</SPAN>, 71 matches)</SPAN><br>image type=Image Link<SPAN class=passed> (Used</SPAN>, 24 matches)</SPAN><br>html id=<SPAN class=passed> (Used</SPAN>, 24 matches)</SPAN><br>name=Image<SPAN class=passed> (Used</SPAN>, 24 matches)</SPAN><br>file name=948f839123af4be7810e78398df3e84c.png<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>class=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>width=80<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:20]]></Time>
<TimeTick>1479112040</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="25" Source="H5Operation" SourceLine="14" >
<Disp><![CDATA["马自达款型"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[马自达款型.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:20]]></Time>
<TimeTick>1479112040</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="26" Source="H5Operation" SourceLine="14" >
<Disp><![CDATA[马自达款型.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" Source="H5Operation" SourceLine="8" >
<Disp><![CDATA[好买车-首页]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:21]]></Time>
<TimeTick>1479112041</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[车型详情页.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:21]]></Time>
<TimeTick>1479112041</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="30" Source="H5Operation" SourceLine="16" >
<Disp><![CDATA[车型详情页.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[去比价按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:23]]></Time>
<TimeTick>1479112043</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="33" Source="H5Operation" SourceLine="18" >
<Disp><![CDATA[去比价按钮.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[第一步和最后一步的下一步.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:24]]></Time>
<TimeTick>1479112044</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="36" Source="H5Operation" SourceLine="20" >
<Disp><![CDATA[第一步和最后一步的下一步.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[第二步款型选择.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:25]]></Time>
<TimeTick>1479112045</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="39" Source="H5Operation" SourceLine="22" >
<Disp><![CDATA[第二步款型选择.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[颜色选择.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:26]]></Time>
<TimeTick>1479112046</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="42" Source="H5Operation" SourceLine="24" >
<Disp><![CDATA[颜色选择.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[拍照选择-上沪牌.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:27]]></Time>
<TimeTick>1479112047</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="45" Source="H5Operation" SourceLine="26" >
<Disp><![CDATA[拍照选择-上沪牌.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[购车方式-全款购车.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:29]]></Time>
<TimeTick>1479112049</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="48" Source="H5Operation" SourceLine="28" >
<Disp><![CDATA[购车方式-全款购车.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[购车时间-3个月.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:30]]></Time>
<TimeTick>1479112050</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="51" Source="H5Operation" SourceLine="30" >
<Disp><![CDATA[购车时间-3个月.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[区域-顾村.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:31]]></Time>
<TimeTick>1479112051</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="54" Source="H5Operation" SourceLine="32" >
<Disp><![CDATA[区域-顾村.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[除去1个4S店.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:32]]></Time>
<TimeTick>1479112052</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="57" Source="H5Operation" SourceLine="34" >
<Disp><![CDATA[除去1个4S店.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[除去第2个4S店.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:33]]></Time>
<TimeTick>1479112053</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="60" Source="H5Operation" SourceLine="36" >
<Disp><![CDATA[除去第2个4S店.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[第一步和最后一步的下一步.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:34]]></Time>
<TimeTick>1479112054</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="63" Source="H5Operation" SourceLine="38" >
<Disp><![CDATA[第一步和最后一步的下一步.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[用户手机号码.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:36]]></Time>
<TimeTick>1479112056</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="66" Source="H5Operation" SourceLine="40" >
<Disp><![CDATA[用户手机号码.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA["老用户提示语"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:58]]></Time>
<TimeTick>1479112078</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="104" status="Warning" Source="H5Operation" SourceLine="61" >
<Disp><![CDATA["老用户提示语"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA["老用户提示语"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=WebElement<br>innertext=欢迎回来，尊敬的好买车用户！<br>html tag=DIV<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (96 objects found)&nbsp;</FONT></u><br>
micclass=WebElement<br>html tag=DIV<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
html id=<SPAN class=passed> (Used</SPAN>, 90 matches)</SPAN><br>class=attention_msg<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>innertext=欢迎回来，尊敬的好买车用户！<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:58]]></Time>
<TimeTick>1479112078</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="105" Source="H5Operation" SourceLine="61" >
<Disp><![CDATA["老用户提示语"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[免费验证码.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:27:59]]></Time>
<TimeTick>1479112079</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="108" Source="H5Operation" SourceLine="79" >
<Disp><![CDATA[免费验证码.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="29" status="Warning" Source="H5Operation" SourceLine="16" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" status="Warning" Source="H5Operation" SourceLine="8" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Action rID="T31">
<AName><![CDATA[adminLogin]]></AName>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:00]]></Time>
<TimeTick>1479112080</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:00]]></Time>
<TimeTick>1479112080</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="113" status="Passed" Source="adminLogin" SourceLine="1" >
<Disp><![CDATA[Run "IExplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="112" status="Passed" Source="adminLogin" SourceLine="1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:02]]></Time>
<TimeTick>1479112082</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA["管理后台系统界面"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (2 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=管理后台系统界面<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>title=管理后台系统界面<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>openurl=res://ieframe.dll/securityatrisk.htm<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=安全设置风险<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hasstatusbar=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hasmenubar=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hastoolbar=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:02]]></Time>
<TimeTick>1479112082</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="116" Source="adminLogin" SourceLine="3" >
<Disp><![CDATA["管理后台系统界面"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:02]]></Time>
<TimeTick>1479112082</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:02]]></Time>
<TimeTick>1479112082</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="119" Source="adminLogin" SourceLine="3" >
<Disp><![CDATA[管理后台系统界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[用户名输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:05]]></Time>
<TimeTick>1479112085</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="122" Source="adminLogin" SourceLine="5" >
<Disp><![CDATA[用户名输入框.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[密码按钮.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Hmc1234"]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:05]]></Time>
<TimeTick>1479112085</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="125" Source="adminLogin" SourceLine="6" >
<Disp><![CDATA[密码按钮.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[登录按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:05]]></Time>
<TimeTick>1479112085</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="128" Source="adminLogin" SourceLine="7" >
<Disp><![CDATA[登录按钮.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="118" Source="adminLogin" SourceLine="3" >
<Disp><![CDATA[管理后台系统界面]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[系统主界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:07]]></Time>
<TimeTick>1479112087</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[系统主界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:07]]></Time>
<TimeTick>1479112087</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="132" Source="adminLogin" SourceLine="9" >
<Disp><![CDATA[系统主界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[短信管理-菜单.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:07]]></Time>
<TimeTick>1479112087</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="135" Source="adminLogin" SourceLine="10" >
<Disp><![CDATA[短信管理-菜单.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[发件箱-短信管理.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:07]]></Time>
<TimeTick>1479112087</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="138" Source="adminLogin" SourceLine="11" >
<Disp><![CDATA[发件箱-短信管理.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[查询条件框架]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:09]]></Time>
<TimeTick>1479112089</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[手机-查询条件.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["17720002624"]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:09]]></Time>
<TimeTick>1479112089</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="142" Source="adminLogin" SourceLine="16" >
<Disp><![CDATA[手机-查询条件.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[查询按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:10]]></Time>
<TimeTick>1479112090</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="145" Source="adminLogin" SourceLine="17" >
<Disp><![CDATA[查询按钮.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA["短信结果表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:13]]></Time>
<TimeTick>1479112093</TimeTick>
<NodeArgs eType="General" icon="15" nRep="147" >
<Disp><![CDATA["短信结果表":Function Call]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="14" nRep="141" Source="adminLogin" SourceLine="16" >
<Disp><![CDATA[查询条件框架]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="131" Source="adminLogin" SourceLine="9" >
<Disp><![CDATA[系统主界面]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="115" Source="adminLogin" SourceLine="3" >
<Disp><![CDATA[管理后台系统界面]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/14 - 16:28:00" eTime="2016/11/14 - 16:28:13" passed="1" failed="0" warnings="0" ><Param ><ParamName><![CDATA[phoneRan]]></ParamName><ParamVal><![CDATA[17720002624]]></ParamVal>
</Param>
<Param ><ParamName><![CDATA[isOlduser]]></ParamName><ParamVal><![CDATA[-1]]></ParamVal>
</Param>
<Param paramInOut = "Out"><ParamName><![CDATA[verifyCode]]></ParamName><ParamVal><![CDATA[0423]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="4" nRep="109" status="Passed" >
<Disp><![CDATA[adminLogin Summary]]></Disp>
</NodeArgs>
</Action>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:17]]></Time>
<TimeTick>1479112097</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:17]]></Time>
<TimeTick>1479112097</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[输入验证码.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:17]]></Time>
<TimeTick>1479112097</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="153" Source="H5Operation" SourceLine="90" >
<Disp><![CDATA[输入验证码.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[新用户昵称.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:19]]></Time>
<TimeTick>1479112099</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="156" Source="H5Operation" SourceLine="100" >
<Disp><![CDATA[新用户昵称.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[新用户昵称.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["4.0自动化测试帐号1"]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:19]]></Time>
<TimeTick>1479112099</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="159" Source="H5Operation" SourceLine="102" >
<Disp><![CDATA[新用户昵称.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[新用户昵称.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:20]]></Time>
<TimeTick>1479112100</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="162" Source="H5Operation" SourceLine="104" >
<Disp><![CDATA[新用户昵称.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[开始比价.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:22]]></Time>
<TimeTick>1479112102</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="165" Source="H5Operation" SourceLine="108" >
<Disp><![CDATA[开始比价.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:54]]></Time>
<TimeTick>1479112134</TimeTick>
<NodeArgs eType="General" icon="16" nRep="166" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="152" Source="H5Operation" SourceLine="90" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="151" Source="H5Operation" SourceLine="90" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/14 - 16:27:13" eTime="2016/11/14 - 16:28:54" passed="1" failed="0" warnings="1" ><Param ><ParamName><![CDATA[verifyCode]]></ParamName><ParamVal><![CDATA[]]></ParamVal>
</Param>
<Param paramInOut = "Out"><ParamName><![CDATA[phoneRan]]></ParamName><ParamVal><![CDATA[<Not Initialized>]]></ParamVal>
</Param>
<Param paramInOut = "Out"><ParamName><![CDATA[isOlduser]]></ParamName><ParamVal><![CDATA[<Not Initialized>]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Warning" >
<Disp><![CDATA[H5Operation Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Warning" >
<Disp><![CDATA[1114-HMC-H5-比价 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2016/11/14 - 16:28:54]]></Time>
<TimeTick>1479112134</TimeTick>
<NodeArgs eType="General" icon="17" nRep="169" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/14 - 16:27:12" eTime="2016/11/14 - 16:28:54" passed="2" failed="0" warnings="1" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Warning" >
<Disp><![CDATA[Test 1114-HMC-H5-比价 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>