<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="VICTOR-PC"><DocLocation><![CDATA[C:\Unified Functional Testing\4.0\1116-HMC-PC-报价-模块化]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[1116-HMC-PC-报价-模块化]]></DName>
<Res><![CDATA[Res21]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[00MainAction]]></AName>
<Action rID="T5">
<AName><![CDATA[01AdminLogin]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:09]]></Time>
<TimeTick>1480387689</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:09]]></Time>
<TimeTick>1480387689</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" Source="01AdminLogin" SourceLine="4" >
<Disp><![CDATA[Run "IExplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="01AdminLogin" SourceLine="4" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:11]]></Time>
<TimeTick>1480387691</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:11]]></Time>
<TimeTick>1480387691</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:11]]></Time>
<TimeTick>1480387691</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" Source="01AdminLogin" SourceLine="7" >
<Disp><![CDATA[管理后台系统界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[用户名输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:14]]></Time>
<TimeTick>1480387694</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" Source="01AdminLogin" SourceLine="9" >
<Disp><![CDATA[用户名输入框.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[密码输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Hmc1234"]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:14]]></Time>
<TimeTick>1480387694</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" Source="01AdminLogin" SourceLine="10" >
<Disp><![CDATA[密码输入框.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[登录按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:14]]></Time>
<TimeTick>1480387694</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="26" Source="01AdminLogin" SourceLine="11" >
<Disp><![CDATA[登录按钮.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="16" Source="01AdminLogin" SourceLine="7" >
<Disp><![CDATA[管理后台系统界面]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" Source="01AdminLogin" SourceLine="7" >
<Disp><![CDATA[管理后台系统界面]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/29 - 10:48:09" eTime="2016/11/29 - 10:48:15" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Passed" >
<Disp><![CDATA[01AdminLogin Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T14">
<AName><![CDATA[02AdminOperation]]></AName>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[系统主界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:17]]></Time>
<TimeTick>1480387697</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[系统主界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:17]]></Time>
<TimeTick>1480387697</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[系统主界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:17]]></Time>
<TimeTick>1480387697</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="33" Source="02AdminOperation" SourceLine="2" >
<Disp><![CDATA[系统主界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[订单管理-菜单.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:17]]></Time>
<TimeTick>1480387697</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="36" Source="02AdminOperation" SourceLine="3" >
<Disp><![CDATA[订单管理-菜单.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[待报报价单-订单管理-预发环境.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:19]]></Time>
<TimeTick>1480387699</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="40" Source="02AdminOperation" SourceLine="6" >
<Disp><![CDATA[待报报价单-订单管理-预发环境.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[待报价信息框架]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:24]]></Time>
<TimeTick>1480387704</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:24]]></Time>
<TimeTick>1480387704</TimeTick>
<NodeArgs eType="General" icon="13" nRep="43" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:24]]></Time>
<TimeTick>1480387704</TimeTick>
<NodeArgs eType="General" icon="13" nRep="44" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:24]]></Time>
<TimeTick>1480387704</TimeTick>
<NodeArgs eType="General" icon="13" nRep="45" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:24]]></Time>
<TimeTick>1480387704</TimeTick>
<NodeArgs eType="General" icon="13" nRep="46" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:24]]></Time>
<TimeTick>1480387704</TimeTick>
<NodeArgs eType="General" icon="13" nRep="47" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ 捷豹路虎江杨南路店 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:24]]></Time>
<TimeTick>1480387704</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="49" Source="02AdminOperation" SourceLine="42" >
<Disp><![CDATA[[ 捷豹路虎江杨南路店 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA["4S店人员信息":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:33]]></Time>
<TimeTick>1480387713</TimeTick>
<NodeArgs eType="General" icon="13" nRep="51" >
<Disp><![CDATA["4S店人员信息":Function Call]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="42" Source="02AdminOperation" SourceLine="19" >
<Disp><![CDATA[待报价信息框架]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="32" Source="02AdminOperation" SourceLine="2" >
<Disp><![CDATA[系统主界面]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="31" Source="02AdminOperation" SourceLine="2" >
<Disp><![CDATA[系统主界面]]></Disp>
</NodeArgs>
</Step>
<Action rID="T28">
<AName><![CDATA[03Merchant]]></AName>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:35]]></Time>
<TimeTick>1480387715</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:35]]></Time>
<TimeTick>1480387715</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="56" status="Passed" Source="03Merchant" SourceLine="6" >
<Disp><![CDATA[Run "IExplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="55" status="Passed" Source="03Merchant" SourceLine="6" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[4S店后台管理系统登录界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:37]]></Time>
<TimeTick>1480387717</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[4S店后台管理系统登录界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:37]]></Time>
<TimeTick>1480387717</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="59" Source="03Merchant" SourceLine="8" >
<Disp><![CDATA[4S店后台管理系统登录界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[登录界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:37]]></Time>
<TimeTick>1480387717</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[用户名输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["XSHXJJBLH002"]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:37]]></Time>
<TimeTick>1480387717</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="63" Source="03Merchant" SourceLine="10" >
<Disp><![CDATA[用户名输入框.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[密码输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["123456"]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:37]]></Time>
<TimeTick>1480387717</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="66" Source="03Merchant" SourceLine="11" >
<Disp><![CDATA[密码输入框.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[登录按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:38]]></Time>
<TimeTick>1480387718</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="69" Source="03Merchant" SourceLine="13" >
<Disp><![CDATA[登录按钮.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="62" Source="03Merchant" SourceLine="10" >
<Disp><![CDATA[登录界面]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[商户端操作界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:39]]></Time>
<TimeTick>1480387719</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[商户端操作界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:39]]></Time>
<TimeTick>1480387719</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="73" Source="03Merchant" SourceLine="15" >
<Disp><![CDATA[商户端操作界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[请报价-菜单.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:40]]></Time>
<TimeTick>1480387720</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="76" Source="03Merchant" SourceLine="17" >
<Disp><![CDATA[请报价-菜单.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[待报价列表框架]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:44]]></Time>
<TimeTick>1480387724</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA["待报价单列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:44]]></Time>
<TimeTick>1480387724</TimeTick>
<NodeArgs eType="General" icon="13" nRep="79" >
<Disp><![CDATA["待报价单列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA["待报价单列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:44]]></Time>
<TimeTick>1480387724</TimeTick>
<NodeArgs eType="General" icon="13" nRep="80" >
<Disp><![CDATA["待报价单列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ 去报价 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:44]]></Time>
<TimeTick>1480387724</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="82" Source="03Merchant" SourceLine="27" >
<Disp><![CDATA[[ 去报价 ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="78" Source="03Merchant" SourceLine="24" >
<Disp><![CDATA[待报价列表框架]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[去报价详情框架]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:46]]></Time>
<TimeTick>1480387726</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[车源单选按钮.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#3"]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:46]]></Time>
<TimeTick>1480387726</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="86" Source="03Merchant" SourceLine="36" >
<Disp><![CDATA[车源单选按钮.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[优惠比例.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["6.7"]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:46]]></Time>
<TimeTick>1480387726</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="89" Source="03Merchant" SourceLine="57" >
<Disp><![CDATA[优惠比例.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA["保险税费表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:46]]></Time>
<TimeTick>1480387726</TimeTick>
<NodeArgs eType="General" icon="13" nRep="91" >
<Disp><![CDATA["保险税费表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA["免费询价-右侧简图":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:46]]></Time>
<TimeTick>1480387726</TimeTick>
<NodeArgs eType="General" icon="13" nRep="93" >
<Disp><![CDATA["免费询价-右侧简图":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[综合服务费.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["3000"]]></Details>
<Time><![CDATA[2016/11/29 - 10:48:47]]></Time>
<TimeTick>1480387727</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="96" Source="03Merchant" SourceLine="79" >
<Disp><![CDATA[综合服务费.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA["是否可自主回原籍单选框"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2016/11/29 - 10:49:09]]></Time>
<TimeTick>1480387749</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="136" status="Warning" Source="03Merchant" SourceLine="96" >
<Disp><![CDATA["是否可自主回原籍单选框"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA["是否可自主回原籍单选框"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>visible=-1<br>name=licence<br>micclass=WebRadioGroup<br>html tag=INPUT<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (2 objects found)&nbsp;</FONT></u><br>
micclass=WebRadioGroup<br>html tag=INPUT<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=licence<SPAN class=Failed> (Skipped)</SPAN><br>html id=lrd3<SPAN class=Failed> (Skipped)</SPAN><br>class=<SPAN class=Failed> (Skipped)</SPAN><br>items count=2<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2016/11/29 - 10:49:09]]></Time>
<TimeTick>1480387749</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="137" Source="03Merchant" SourceLine="96" >
<Disp><![CDATA["是否可自主回原籍单选框"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA["是否可自主回原籍单选框"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2016/11/29 - 10:49:30]]></Time>
<TimeTick>1480387770</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="178" status="Warning" Source="03Merchant" SourceLine="115" >
<Disp><![CDATA["是否可自主回原籍单选框"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA["是否可自主回原籍单选框"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>visible=-1<br>name=licence<br>micclass=WebRadioGroup<br>html tag=INPUT<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (2 objects found)&nbsp;</FONT></u><br>
micclass=WebRadioGroup<br>html tag=INPUT<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=licence<SPAN class=Failed> (Skipped)</SPAN><br>html id=lrd3<SPAN class=Failed> (Skipped)</SPAN><br>class=<SPAN class=Failed> (Skipped)</SPAN><br>items count=2<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2016/11/29 - 10:49:30]]></Time>
<TimeTick>1480387770</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="179" Source="03Merchant" SourceLine="115" >
<Disp><![CDATA["是否可自主回原籍单选框"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[是否可自主回原籍单选框.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#0"]]></Details>
<Time><![CDATA[2016/11/29 - 10:49:30]]></Time>
<TimeTick>1480387770</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="180" Source="03Merchant" SourceLine="115" >
<Disp><![CDATA[是否可自主回原籍单选框.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[推荐可上外牌.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2016/11/29 - 10:49:30]]></Time>
<TimeTick>1480387770</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="183" Source="03Merchant" SourceLine="119" >
<Disp><![CDATA[推荐可上外牌.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[牌照费用.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1500"]]></Details>
<Time><![CDATA[2016/11/29 - 10:49:32]]></Time>
<TimeTick>1480387772</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="186" Source="03Merchant" SourceLine="138" >
<Disp><![CDATA[牌照费用.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[推荐外牌-省]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "推荐外牌-省" (of class WebList). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[2016/11/29 - 10:49:54]]></Time>
<TimeTick>1480387794</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[推荐外牌-省]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>miccommentproperty = <br>Mercury Class = WebList<br>Html Tag = SELECT<br>_xpath = //TR[3]/TD[1]/SPAN[1]/SELECT[1]<br>|Visible Items = 0<br>Visible = -1<br>Name = prov<br>Items Count = 32<br>Html Id = <br>default value = <br>DHTML Class = input_sel w100<br>]]></Details>
<Time><![CDATA[2016/11/29 - 10:49:54]]></Time>
<TimeTick>1480387794</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="227" status="Warning" nType="Description" Source="03Merchant" SourceLine="140" >
<Disp><![CDATA[推荐外牌-省]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="17" nRep="226" status="Failed" nType="Run Error" Source="03Merchant" SourceLine="140" >
<Disp><![CDATA[推荐外牌-省]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="85" status="Failed" Source="03Merchant" SourceLine="36" >
<Disp><![CDATA[去报价详情框架]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="72" status="Failed" Source="03Merchant" SourceLine="15" >
<Disp><![CDATA[商户端操作界面]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="58" status="Failed" Source="03Merchant" SourceLine="8" >
<Disp><![CDATA[4S店后台管理系统登录界面]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;推荐外牌-省&quot; (of class WebList). Verify that this object's properties match an object currently displayed in your application.<BR>Line (141): &quot;Browser(&quot;4S店后台管理系统登录界面&quot;).Page(&quot;商户端操作界面&quot;).Frame(&quot;去报价详情框架&quot;).WebList(&quot;推荐外牌-省&quot;).Select &quot;安徽&quot;&quot;. ]]></Details>
<Time><![CDATA[2016/11/29 - 10:49:54]]></Time>
<TimeTick>1480387794</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="228" status="Failed" Source="03Merchant" SourceLine="140" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2016/11/29 - 10:50:58]]></Time>
<TimeTick>1480387858</TimeTick>
<NodeArgs eType="General" icon="19" nRep="229" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/29 - 10:48:35" eTime="2016/11/29 - 10:50:58" passed="1" failed="2" warnings="3" ><Param ><ParamName><![CDATA[fsEmployee]]></ParamName><ParamVal><![CDATA[XSHXJJBLH002]]></ParamVal>
</Param>
<Param ><ParamName><![CDATA[quoteRowcount]]></ParamName><ParamVal><![CDATA[]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="4" nRep="52" status="Failed" >
<Disp><![CDATA[03Merchant Summary]]></Disp>
</NodeArgs>
</Action>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2016/11/29 - 10:50:58]]></Time>
<TimeTick>1480387858</TimeTick>
<NodeArgs eType="General" icon="19" nRep="231" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/29 - 10:48:17" eTime="2016/11/29 - 10:50:58" passed="0" failed="0" warnings="0" ><Param paramInOut = "Out"><ParamName><![CDATA[fsEmployee]]></ParamName><ParamVal><![CDATA[<Not Initialized>]]></ParamVal>
</Param>
<Param paramInOut = "Out"><ParamName><![CDATA[quoteRowcount]]></ParamName><ParamVal><![CDATA[<Not Initialized>]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="4" nRep="28" status="Failed" >
<Disp><![CDATA[02AdminOperation Summary]]></Disp>
</NodeArgs>
</Action>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2016/11/29 - 10:50:58]]></Time>
<TimeTick>1480387858</TimeTick>
<NodeArgs eType="General" icon="19" nRep="233" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/29 - 10:48:09" eTime="2016/11/29 - 10:50:58" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[00MainAction Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[1116-HMC-PC-报价-模块化 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2016/11/29 - 10:48:08" eTime="2016/11/29 - 10:50:58" passed="2" failed="2" warnings="3" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test 1116-HMC-PC-报价-模块化 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>