<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="VICTOR-PC"><DocLocation><![CDATA[C:\Unified Functional Testing\4.0\1116-HMC-PC-报价-模块化]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[1116-HMC-PC-报价-模块化]]></DName>
<Res><![CDATA[Res5]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[00MainAction]]></AName>
<Action rID="T5">
<AName><![CDATA[01AdminLogin]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/11/24 - 11:20:27]]></Time>
<TimeTick>1479957627</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Details>
<Time><![CDATA[2016/11/24 - 11:20:27]]></Time>
<TimeTick>1479957627</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" Source="01AdminLogin" SourceLine="2" >
<Disp><![CDATA[Run "IExplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="01AdminLogin" SourceLine="2" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/24 - 11:20:28]]></Time>
<TimeTick>1479957628</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/24 - 11:20:28]]></Time>
<TimeTick>1479957628</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 11:20:28]]></Time>
<TimeTick>1479957628</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" Source="01AdminLogin" SourceLine="4" >
<Disp><![CDATA[管理后台系统界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[用户名输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[2016/11/24 - 11:20:31]]></Time>
<TimeTick>1479957631</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" Source="01AdminLogin" SourceLine="6" >
<Disp><![CDATA[用户名输入框.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[密码输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Hmc1234"]]></Details>
<Time><![CDATA[2016/11/24 - 11:20:32]]></Time>
<TimeTick>1479957632</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" Source="01AdminLogin" SourceLine="7" >
<Disp><![CDATA[密码输入框.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[登录按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 11:20:32]]></Time>
<TimeTick>1479957632</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="26" Source="01AdminLogin" SourceLine="8" >
<Disp><![CDATA[登录按钮.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="16" Source="01AdminLogin" SourceLine="4" >
<Disp><![CDATA[管理后台系统界面]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" Source="01AdminLogin" SourceLine="4" >
<Disp><![CDATA[管理后台系统界面]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/24 - 11:20:27" eTime="2016/11/24 - 11:20:33" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Passed" >
<Disp><![CDATA[01AdminLogin Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T14">
<AName><![CDATA[02AdminOperation]]></AName>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[系统主界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/24 - 11:20:34]]></Time>
<TimeTick>1479957634</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[系统主界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/24 - 11:20:34]]></Time>
<TimeTick>1479957634</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[系统主界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 11:20:34]]></Time>
<TimeTick>1479957634</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="33" Source="02AdminOperation" SourceLine="2" >
<Disp><![CDATA[系统主界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[订单管理-菜单.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 11:20:34]]></Time>
<TimeTick>1479957634</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="36" Source="02AdminOperation" SourceLine="3" >
<Disp><![CDATA[订单管理-菜单.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA["待报报价单-订单管理"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2016/11/24 - 11:20:56]]></Time>
<TimeTick>1479957656</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="75" status="Warning" Source="02AdminOperation" SourceLine="5" >
<Disp><![CDATA["待报报价单-订单管理"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA["待报报价单-订单管理"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=待报报价单(21)<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (90 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
text=待报报价单(21)<SPAN class=Failed> (Skipped)</SPAN><br>html id=<SPAN class=passed> (Used</SPAN>, 88 matches)</SPAN><br>class=<SPAN class=passed> (Used</SPAN>, 68 matches)</SPAN><br>name=待报报价单(21)<SPAN class=Failed> (Skipped)</SPAN><br>href=http://oms-test.haomaiche.com/admin/web/webRespond.jsp?param=1<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2016/11/24 - 11:20:56]]></Time>
<TimeTick>1479957656</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="76" Source="02AdminOperation" SourceLine="5" >
<Disp><![CDATA["待报报价单-订单管理"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[待报报价单-订单管理.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 11:20:56]]></Time>
<TimeTick>1479957656</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="77" Source="02AdminOperation" SourceLine="5" >
<Disp><![CDATA[待报报价单-订单管理.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[待报价信息框架]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:02]]></Time>
<TimeTick>1479957662</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:02]]></Time>
<TimeTick>1479957662</TimeTick>
<NodeArgs eType="General" icon="14" nRep="80" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:02]]></Time>
<TimeTick>1479957662</TimeTick>
<NodeArgs eType="General" icon="14" nRep="81" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:02]]></Time>
<TimeTick>1479957662</TimeTick>
<NodeArgs eType="General" icon="14" nRep="82" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:02]]></Time>
<TimeTick>1479957662</TimeTick>
<NodeArgs eType="General" icon="14" nRep="83" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:02]]></Time>
<TimeTick>1479957662</TimeTick>
<NodeArgs eType="General" icon="14" nRep="84" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ 测试4S店1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:02]]></Time>
<TimeTick>1479957662</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="86" Source="02AdminOperation" SourceLine="40" >
<Disp><![CDATA[[ 测试4S店1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA["4S店人员信息":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:10]]></Time>
<TimeTick>1479957670</TimeTick>
<NodeArgs eType="General" icon="14" nRep="88" >
<Disp><![CDATA["4S店人员信息":Function Call]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="79" Source="02AdminOperation" SourceLine="17" >
<Disp><![CDATA[待报价信息框架]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="32" status="Warning" Source="02AdminOperation" SourceLine="2" >
<Disp><![CDATA[系统主界面]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="31" status="Warning" Source="02AdminOperation" SourceLine="2" >
<Disp><![CDATA[系统主界面]]></Disp>
</NodeArgs>
</Step>
<Action rID="T30">
<AName><![CDATA[03Merchant]]></AName>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:18]]></Time>
<TimeTick>1479957678</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:18]]></Time>
<TimeTick>1479957678</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="93" status="Passed" Source="03Merchant" SourceLine="5" >
<Disp><![CDATA[Run "IExplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="92" status="Passed" Source="03Merchant" SourceLine="5" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[4S店后台管理系统登录界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:19]]></Time>
<TimeTick>1479957679</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[4S店后台管理系统登录界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:19]]></Time>
<TimeTick>1479957679</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="96" Source="03Merchant" SourceLine="7" >
<Disp><![CDATA[4S店后台管理系统登录界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[登录界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:19]]></Time>
<TimeTick>1479957679</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[用户名输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ge"]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:19]]></Time>
<TimeTick>1479957679</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="100" Source="03Merchant" SourceLine="9" >
<Disp><![CDATA[用户名输入框.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[密码输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["123456"]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:19]]></Time>
<TimeTick>1479957679</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="103" Source="03Merchant" SourceLine="10" >
<Disp><![CDATA[密码输入框.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[登录按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:20]]></Time>
<TimeTick>1479957680</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="106" Source="03Merchant" SourceLine="12" >
<Disp><![CDATA[登录按钮.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="99" Source="03Merchant" SourceLine="9" >
<Disp><![CDATA[登录界面]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[商户端操作界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:22]]></Time>
<TimeTick>1479957682</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[商户端操作界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:22]]></Time>
<TimeTick>1479957682</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="110" Source="03Merchant" SourceLine="14" >
<Disp><![CDATA[商户端操作界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA["请报价-菜单"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:44]]></Time>
<TimeTick>1479957704</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="152" status="Warning" Source="03Merchant" SourceLine="16" >
<Disp><![CDATA["请报价-菜单"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA["请报价-菜单"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=请报价 （4）<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (42 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
text=请报价 （4）<SPAN class=Failed> (Skipped)</SPAN><br>html id=<SPAN class=passed> (Used</SPAN>, 38 matches)</SPAN><br>class=<SPAN class=passed> (Used</SPAN>, 20 matches)</SPAN><br>name=请报价 （4）<SPAN class=Failed> (Skipped)</SPAN><br>href=http://mps-test.haomaiche.com/fs/fs/fsAskPrice.html<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:44]]></Time>
<TimeTick>1479957704</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="153" Source="03Merchant" SourceLine="16" >
<Disp><![CDATA["请报价-菜单"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[请报价-菜单.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:44]]></Time>
<TimeTick>1479957704</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="154" Source="03Merchant" SourceLine="16" >
<Disp><![CDATA[请报价-菜单.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[待报价列表框架]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:47]]></Time>
<TimeTick>1479957707</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA["待报价单列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:47]]></Time>
<TimeTick>1479957707</TimeTick>
<NodeArgs eType="General" icon="14" nRep="157" >
<Disp><![CDATA["待报价单列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA["待报价单列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:47]]></Time>
<TimeTick>1479957707</TimeTick>
<NodeArgs eType="General" icon="14" nRep="158" >
<Disp><![CDATA["待报价单列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ 去报价 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:47]]></Time>
<TimeTick>1479957707</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="160" Source="03Merchant" SourceLine="26" >
<Disp><![CDATA[[ 去报价 ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="156" Source="03Merchant" SourceLine="23" >
<Disp><![CDATA[待报价列表框架]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[去报价详情框架]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:48]]></Time>
<TimeTick>1479957708</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[车源单选按钮.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#3"]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:48]]></Time>
<TimeTick>1479957708</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="164" Source="03Merchant" SourceLine="35" >
<Disp><![CDATA[车源单选按钮.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[优惠比例.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["6.7"]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:49]]></Time>
<TimeTick>1479957709</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="167" Source="03Merchant" SourceLine="56" >
<Disp><![CDATA[优惠比例.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA["保险税费表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:49]]></Time>
<TimeTick>1479957709</TimeTick>
<NodeArgs eType="General" icon="14" nRep="169" >
<Disp><![CDATA["保险税费表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA["免费询价-右侧简图":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:49]]></Time>
<TimeTick>1479957709</TimeTick>
<NodeArgs eType="General" icon="14" nRep="171" >
<Disp><![CDATA["免费询价-右侧简图":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[综合服务费.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["3000"]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:50]]></Time>
<TimeTick>1479957710</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="174" Source="03Merchant" SourceLine="78" >
<Disp><![CDATA[综合服务费.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[是否可自主回原籍单选框.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#0"]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:52]]></Time>
<TimeTick>1479957712</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="179" Source="03Merchant" SourceLine="109" >
<Disp><![CDATA[是否可自主回原籍单选框.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA["牌照费用"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>type=text<br>name=license_Price<br>micclass=WebEdit<br>html tag=INPUT<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (12 objects found)&nbsp;</FONT></u><br>
type=text<br>micclass=WebEdit<br>html tag=INPUT<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=license_Price<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>html id=huPrice<SPAN class=Failed> (Skipped)</SPAN><br>max length=2147483647<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>default value=3000<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>class=addFee checkinput<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>rows=0<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>visible=1<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:54]]></Time>
<TimeTick>1479957714</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="182" Source="03Merchant" SourceLine="116" >
<Disp><![CDATA["牌照费用"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[牌照费用.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1500"]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:54]]></Time>
<TimeTick>1479957714</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="183" Source="03Merchant" SourceLine="116" >
<Disp><![CDATA[牌照费用.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[推荐外牌-省.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["安徽"]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:55]]></Time>
<TimeTick>1479957715</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="186" Source="03Merchant" SourceLine="118" >
<Disp><![CDATA[推荐外牌-省.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[推荐外牌-城市.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["安庆"]]></Details>
<Time><![CDATA[2016/11/24 - 11:21:56]]></Time>
<TimeTick>1479957716</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="189" Source="03Merchant" SourceLine="120" >
<Disp><![CDATA[推荐外牌-城市.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA["贷款补贴"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2016/11/24 - 11:22:17]]></Time>
<TimeTick>1479957737</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="229" status="Warning" Source="03Merchant" SourceLine="143" >
<Disp><![CDATA["贷款补贴"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA["贷款补贴"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>visible=-1<br>type=text<br>name=sourceLoan<br>micclass=WebEdit<br>html tag=INPUT<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (12 objects found)&nbsp;</FONT></u><br>
type=text<br>micclass=WebEdit<br>html tag=INPUT<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=sourceLoan<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>html id=sourceLoan<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>max length=2147483647<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>default value=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>class=money<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>rows=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2016/11/24 - 11:22:17]]></Time>
<TimeTick>1479957737</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="230" Source="03Merchant" SourceLine="143" >
<Disp><![CDATA["贷款补贴"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[置换补贴.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2016/11/24 - 11:22:17]]></Time>
<TimeTick>1479957737</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="232" Source="03Merchant" SourceLine="164" >
<Disp><![CDATA[置换补贴.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[置换补贴.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["8000"]]></Details>
<Time><![CDATA[2016/11/24 - 11:22:17]]></Time>
<TimeTick>1479957737</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="235" Source="03Merchant" SourceLine="166" >
<Disp><![CDATA[置换补贴.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[颜色加价.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["700"]]></Details>
<Time><![CDATA[2016/11/24 - 11:22:19]]></Time>
<TimeTick>1479957739</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="238" Source="03Merchant" SourceLine="170" >
<Disp><![CDATA[颜色加价.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[现金加价.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["900"]]></Details>
<Time><![CDATA[2016/11/24 - 11:22:20]]></Time>
<TimeTick>1479957740</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="241" Source="03Merchant" SourceLine="172" >