<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="VICTOR-PC"><DocLocation><![CDATA[C:\Unified Functional Testing\4.0\1116-HMC-PC-报价-模块化]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[1116-HMC-PC-报价-模块化]]></DName>
<Res><![CDATA[Res22]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[00MainAction]]></AName>
<Action rID="T5">
<AName><![CDATA[01AdminLogin]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/11/29 - 10:53:54]]></Time>
<TimeTick>1480388034</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Details>
<Time><![CDATA[2016/11/29 - 10:53:54]]></Time>
<TimeTick>1480388034</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" Source="01AdminLogin" SourceLine="4" >
<Disp><![CDATA[Run "IExplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="01AdminLogin" SourceLine="4" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/29 - 10:53:55]]></Time>
<TimeTick>1480388035</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/29 - 10:53:55]]></Time>
<TimeTick>1480388035</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:53:55]]></Time>
<TimeTick>1480388035</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" Source="01AdminLogin" SourceLine="7" >
<Disp><![CDATA[管理后台系统界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[用户名输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[2016/11/29 - 10:53:58]]></Time>
<TimeTick>1480388038</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" Source="01AdminLogin" SourceLine="9" >
<Disp><![CDATA[用户名输入框.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[密码输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Hmc1234"]]></Details>
<Time><![CDATA[2016/11/29 - 10:53:59]]></Time>
<TimeTick>1480388039</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" Source="01AdminLogin" SourceLine="10" >
<Disp><![CDATA[密码输入框.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[登录按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:53:59]]></Time>
<TimeTick>1480388039</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="26" Source="01AdminLogin" SourceLine="11" >
<Disp><![CDATA[登录按钮.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="16" Source="01AdminLogin" SourceLine="7" >
<Disp><![CDATA[管理后台系统界面]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" Source="01AdminLogin" SourceLine="7" >
<Disp><![CDATA[管理后台系统界面]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/11/29 - 10:53:54" eTime="2016/11/29 - 10:54:00" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Passed" >
<Disp><![CDATA[01AdminLogin Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T14">
<AName><![CDATA[02AdminOperation]]></AName>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[系统主界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:01]]></Time>
<TimeTick>1480388041</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[系统主界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:01]]></Time>
<TimeTick>1480388041</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[系统主界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:01]]></Time>
<TimeTick>1480388041</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="33" Source="02AdminOperation" SourceLine="2" >
<Disp><![CDATA[系统主界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[订单管理-菜单.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:01]]></Time>
<TimeTick>1480388041</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="36" Source="02AdminOperation" SourceLine="3" >
<Disp><![CDATA[订单管理-菜单.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[待报报价单-订单管理-预发环境.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:03]]></Time>
<TimeTick>1480388043</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="40" Source="02AdminOperation" SourceLine="6" >
<Disp><![CDATA[待报报价单-订单管理-预发环境.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[待报价信息框架]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:08]]></Time>
<TimeTick>1480388048</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:08]]></Time>
<TimeTick>1480388048</TimeTick>
<NodeArgs eType="General" icon="13" nRep="43" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:08]]></Time>
<TimeTick>1480388048</TimeTick>
<NodeArgs eType="General" icon="13" nRep="44" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:08]]></Time>
<TimeTick>1480388048</TimeTick>
<NodeArgs eType="General" icon="13" nRep="45" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:08]]></Time>
<TimeTick>1480388048</TimeTick>
<NodeArgs eType="General" icon="13" nRep="46" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA["待报价列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:08]]></Time>
<TimeTick>1480388048</TimeTick>
<NodeArgs eType="General" icon="13" nRep="47" >
<Disp><![CDATA["待报价列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ 捷豹路虎江杨南路店 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:08]]></Time>
<TimeTick>1480388048</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="49" Source="02AdminOperation" SourceLine="42" >
<Disp><![CDATA[[ 捷豹路虎江杨南路店 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA["4S店人员信息":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:17]]></Time>
<TimeTick>1480388057</TimeTick>
<NodeArgs eType="General" icon="13" nRep="51" >
<Disp><![CDATA["4S店人员信息":Function Call]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="42" Source="02AdminOperation" SourceLine="19" >
<Disp><![CDATA[待报价信息框架]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="32" Source="02AdminOperation" SourceLine="2" >
<Disp><![CDATA[系统主界面]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="31" Source="02AdminOperation" SourceLine="2" >
<Disp><![CDATA[系统主界面]]></Disp>
</NodeArgs>
</Step>
<Action rID="T28">
<AName><![CDATA[03Merchant]]></AName>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:20]]></Time>
<TimeTick>1480388060</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:20]]></Time>
<TimeTick>1480388060</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="56" status="Passed" Source="03Merchant" SourceLine="6" >
<Disp><![CDATA[Run "IExplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="55" status="Passed" Source="03Merchant" SourceLine="6" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[4S店后台管理系统登录界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:21]]></Time>
<TimeTick>1480388061</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[4S店后台管理系统登录界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:21]]></Time>
<TimeTick>1480388061</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="59" Source="03Merchant" SourceLine="8" >
<Disp><![CDATA[4S店后台管理系统登录界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[登录界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:21]]></Time>
<TimeTick>1480388061</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[用户名输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["XSHXJJBLH002"]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:21]]></Time>
<TimeTick>1480388061</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="63" Source="03Merchant" SourceLine="10" >
<Disp><![CDATA[用户名输入框.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[密码输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["123456"]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:21]]></Time>
<TimeTick>1480388061</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="66" Source="03Merchant" SourceLine="11" >
<Disp><![CDATA[密码输入框.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[登录按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:22]]></Time>
<TimeTick>1480388062</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="69" Source="03Merchant" SourceLine="13" >
<Disp><![CDATA[登录按钮.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="62" Source="03Merchant" SourceLine="10" >
<Disp><![CDATA[登录界面]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[商户端操作界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:23]]></Time>
<TimeTick>1480388063</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[商户端操作界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:23]]></Time>
<TimeTick>1480388063</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="73" Source="03Merchant" SourceLine="15" >
<Disp><![CDATA[商户端操作界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[请报价-菜单.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:24]]></Time>
<TimeTick>1480388064</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="76" Source="03Merchant" SourceLine="17" >
<Disp><![CDATA[请报价-菜单.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[待报价列表框架]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:28]]></Time>
<TimeTick>1480388068</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA["待报价单列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:28]]></Time>
<TimeTick>1480388068</TimeTick>
<NodeArgs eType="General" icon="13" nRep="79" >
<Disp><![CDATA["待报价单列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA["待报价单列表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:28]]></Time>
<TimeTick>1480388068</TimeTick>
<NodeArgs eType="General" icon="13" nRep="80" >
<Disp><![CDATA["待报价单列表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ 去报价 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:28]]></Time>
<TimeTick>1480388068</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="82" Source="03Merchant" SourceLine="27" >
<Disp><![CDATA[[ 去报价 ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="78" Source="03Merchant" SourceLine="24" >
<Disp><![CDATA[待报价列表框架]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[去报价详情框架]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:29]]></Time>
<TimeTick>1480388069</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[车源单选按钮.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#1"]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:29]]></Time>
<TimeTick>1480388069</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="86" Source="03Merchant" SourceLine="36" >
<Disp><![CDATA[车源单选按钮.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[优惠比例.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["6.7"]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:29]]></Time>
<TimeTick>1480388069</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="89" Source="03Merchant" SourceLine="57" >
<Disp><![CDATA[优惠比例.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA["保险税费表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:29]]></Time>
<TimeTick>1480388069</TimeTick>
<NodeArgs eType="General" icon="13" nRep="91" >
<Disp><![CDATA["保险税费表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA["免费询价-右侧简图":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:29]]></Time>
<TimeTick>1480388069</TimeTick>
<NodeArgs eType="General" icon="13" nRep="93" >
<Disp><![CDATA["免费询价-右侧简图":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[综合服务费.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["3000"]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:31]]></Time>
<TimeTick>1480388071</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="96" Source="03Merchant" SourceLine="79" >
<Disp><![CDATA[综合服务费.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA["是否可自主回原籍单选框"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:53]]></Time>
<TimeTick>1480388093</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="136" status="Warning" Source="03Merchant" SourceLine="96" >
<Disp><![CDATA["是否可自主回原籍单选框"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA["是否可自主回原籍单选框"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>visible=-1<br>name=licence<br>micclass=WebRadioGroup<br>html tag=INPUT<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (2 objects found)&nbsp;</FONT></u><br>
micclass=WebRadioGroup<br>html tag=INPUT<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=licence<SPAN class=Failed> (Skipped)</SPAN><br>html id=lrd3<SPAN class=Failed> (Skipped)</SPAN><br>class=<SPAN class=Failed> (Skipped)</SPAN><br>items count=2<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2016/11/29 - 10:54:53]]></Time>
<TimeTick>1480388093</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="137" Source="03Merchant" SourceLine="96" >
<Disp><![CDATA["是否可自主回原籍单选框"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA["是否可自主回原籍单选框"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2016/11/29 - 10:55:14]]></Time>
<TimeTick>1480388114</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="178" status="Warning" Source="03Merchant" SourceLine="115" >
<Disp><![CDATA["是否可自主回原籍单选框"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA["是否可自主回原籍单选框"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>visible=-1<br>name=licence<br>micclass=WebRadioGroup<br>html tag=INPUT<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (2 objects found)&nbsp;</FONT></u><br>
micclass=WebRadioGroup<br>html tag=INPUT<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=licence<SPAN class=Failed> (Skipped)</SPAN><br>html id=lrd3<SPAN class=Failed> (Skipped)</SPAN><br>class=<SPAN class=Failed> (Skipped)</SPAN><br>items count=2<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2016/11/29 - 10:55:14]]></Time>
<TimeTick>1480388114</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="179" Source="03Merchant" SourceLine="115" >
<Disp><![CDATA["是否可自主回原籍单选框"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[是否可自主回原籍单选框.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#1"]]></Details>
<Time><![CDATA[2016/11/29 - 10:55:14]]></Time>
<TimeTick>1480388114</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="180" Source="03Merchant" SourceLine="115" >
<Disp><![CDATA[是否可自主回原籍单选框.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[推荐可上外牌.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2016/11/29 - 10:55:14]]></Time>
<TimeTick>1480388114</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="183" Source="03Merchant" SourceLine="119" >
<Disp><![CDATA[推荐可上外牌.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[牌照费用.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1500"]]></Details>
<Time><![CDATA[2016/11/29 - 10:55:15]]></Time>
<TimeTick>1480388115</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="186" Source="03Merchant" SourceLine="126" >
<Disp><![CDATA[牌照费用.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA["贷款补贴"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2016/11/29 - 10:55:37]]></Time>
<TimeTick>1480388137</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="227" status="Warning" Source="03Merchant" SourceLine="157" >
<Disp><![CDATA["贷款补贴"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA["贷款补贴"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>visible=-1<br>type=text<br>name=sourceLoan<br>micclass=WebEdit<br>html tag=INPUT<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (10 objects found)&nbsp;</FONT></u><br>
type=text<br>micclass=WebEdit<br>html tag=INPUT<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=sourceLoan<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>html id=sourceLoan<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>max length=2147483647<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>default value=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>class=money<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>rows=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2016/11/29 - 10:55:37]]></Time>
<TimeTick>1480388137</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="228" Source="03Merchant" SourceLine="157" >
<Disp><![CDATA["贷款补贴"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[置换补贴.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2016/11/29 - 10:55:40]]></Time>
<TimeTick>1480388140</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="253" Source="03Merchant" SourceLine="178" >
<Disp><![CDATA[置换补贴.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[颜色加价.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["700"]]></Details>
<Time><![CDATA[2016/11/29 - 10:55:42]]></Time>
<TimeTick>1480388142</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="256" Source="03Merchant" SourceLine="184" >
<Disp><![CDATA[颜色加价.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[现金加价.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["900"]]></Details>
<Time><![CDATA[2016/11/29 - 10:55:43]]></Time>
<TimeTick>1480388143</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="259" Source="03Merchant" SourceLine="186" >
<Disp><![CDATA[现金加价.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[是否提车加装单选项.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#1"]]></Details>
<Time><![CDATA[2016/11/29 - 10:55:44]]></Time>
<TimeTick>1480388144</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="262" Source="03Merchant" SourceLine="195" >
<Disp><![CDATA[是否提车加装单选项.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[提车加装价格.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1200"]]></Details>
<Time><![CDATA[2016/11/29 - 10:55:45]]></Time>
<TimeTick>1480388145</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="265" Source="03Merchant" SourceLine="197" >
<Disp><![CDATA[提车加装价格.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[提交询价单.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/11/29 - 10:55:46]]></Time>
<TimeTick>1480388146</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="268" Source="03Merchant" SourceLine="201" >
<Disp><![CDATA[提交询价单.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA["弹出框内容表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[2016/11/29 - 10:55:48]]></Time>
<TimeTick>1480388148</TimeTick>
<NodeArgs eType="General" icon="13" nRep="270" >
<Disp><![CDATA["弹出框内容表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA["弹出框内容表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/29 - 10:55:48]]></Time>
<TimeTick>1480388148</TimeTick>
<NodeArgs eType="General" icon="13" nRep="271" >
<Disp><![CDATA["弹出框内容表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA["弹出框内容表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/29 - 10:55:48]]></Time>
<TimeTick>1480388148</TimeTick>
<NodeArgs eType="General" icon="13" nRep="272" >
<Disp><![CDATA["弹出框内容表":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA["弹出框内容表":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[2016/11/29 - 10:55:48]]></Time>
<TimeTick>1480388148</TimeTick>