<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="VICTOR-PC"><DocLocation><![CDATA[C:\Unified Functional Testing\4.0\20170328-HMC-H5-比价-模块化]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[20170328-HMC-H5-比价-模块化]]></DName>
<Res><![CDATA[Res11]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[00-MainAction]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:34]]></Time>
<TimeTick>1494830374</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Users\Victor\Desktop\deletefolder.vbs",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Users\Victor\Desktop\deletefolder.vbs",1]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:34]]></Time>
<TimeTick>1494830374</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="00-MainAction" SourceLine="9" >
<Disp><![CDATA[Run "C:\Users\Victor\Desktop\deletefolder.vbs",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="00-MainAction" SourceLine="9" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Action rID="T7">
<AName><![CDATA[01-HomeAction]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:36]]></Time>
<TimeTick>1494830376</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Run "chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "chrome.exe",1]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:36]]></Time>
<TimeTick>1494830376</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="16" status="Passed" Source="01-HomeAction" SourceLine="5" >
<Disp><![CDATA[Run "chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="15" status="Passed" Source="01-HomeAction" SourceLine="5" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:39]]></Time>
<TimeTick>1494830379</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[好买车-首页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:39]]></Time>
<TimeTick>1494830379</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[好买车-首页.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:39]]></Time>
<TimeTick>1494830379</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="21" Source="01-HomeAction" SourceLine="8" >
<Disp><![CDATA[好买车-首页.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[选车去比价-按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:41]]></Time>
<TimeTick>1494830381</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" Source="01-HomeAction" SourceLine="10" >
<Disp><![CDATA[选车去比价-按钮.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="20" Source="01-HomeAction" SourceLine="8" >
<Disp><![CDATA[好买车-首页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="19" Source="01-HomeAction" SourceLine="8" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2017/5/15 - 14:39:35" eTime="2017/5/15 - 14:39:41" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="12" status="Passed" >
<Disp><![CDATA[01-HomeAction Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T14">
<AName><![CDATA[02-CarBrand-Chevrolet]]></AName>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:42]]></Time>
<TimeTick>1494830382</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[好买车-首页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:42]]></Time>
<TimeTick>1494830382</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[雪佛兰-品牌.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:42]]></Time>
<TimeTick>1494830382</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="31" Source="02-CarBrand-Chevrolet" SourceLine="3" >
<Disp><![CDATA[雪佛兰-品牌.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[科迈罗.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:43]]></Time>
<TimeTick>1494830383</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="34" Source="02-CarBrand-Chevrolet" SourceLine="6" >
<Disp><![CDATA[科迈罗.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="30" Source="02-CarBrand-Chevrolet" SourceLine="3" >
<Disp><![CDATA[好买车-首页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="29" Source="02-CarBrand-Chevrolet" SourceLine="3" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2017/5/15 - 14:39:41" eTime="2017/5/15 - 14:39:43" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="26" >
<Disp><![CDATA[02-CarBrand-Chevrolet Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T19">
<AName><![CDATA[03-Trad-Step1]]></AName>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:45]]></Time>
<TimeTick>1494830385</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:45]]></Time>
<TimeTick>1494830385</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[车型详情页.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:45]]></Time>
<TimeTick>1494830385</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="41" Source="03-Trad-Step1" SourceLine="3" >
<Disp><![CDATA[车型详情页.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[选定比价.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:46]]></Time>
<TimeTick>1494830386</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="44" Source="03-Trad-Step1" SourceLine="6" >
<Disp><![CDATA[选定比价.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="40" Source="03-Trad-Step1" SourceLine="3" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="39" Source="03-Trad-Step1" SourceLine="3" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2017/5/15 - 14:39:43" eTime="2017/5/15 - 14:39:47" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="36" >
<Disp><![CDATA[03-Trad-Step1 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T24">
<AName><![CDATA[05-CarColor-Chevrolet]]></AName>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:48]]></Time>
<TimeTick>1494830388</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:48]]></Time>
<TimeTick>1494830388</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[车型详情页.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:48]]></Time>
<TimeTick>1494830388</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="51" Source="05-CarColor-Chevrolet" SourceLine="3" >
<Disp><![CDATA[车型详情页.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[布鲁斯蓝.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:49]]></Time>
<TimeTick>1494830389</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="54" Source="05-CarColor-Chevrolet" SourceLine="5" >
<Disp><![CDATA[布鲁斯蓝.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="50" Source="05-CarColor-Chevrolet" SourceLine="3" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="49" Source="05-CarColor-Chevrolet" SourceLine="3" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2017/5/15 - 14:39:47" eTime="2017/5/15 - 14:39:49" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="46" >
<Disp><![CDATA[05-CarColor-Chevrolet Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T29">
<AName><![CDATA[06-License-huA]]></AName>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:50]]></Time>
<TimeTick>1494830390</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:50]]></Time>
<TimeTick>1494830390</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[牌照选择-上沪牌.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:50]]></Time>
<TimeTick>1494830390</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="61" Source="06-License-huA" SourceLine="2" >
<Disp><![CDATA[牌照选择-上沪牌.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="60" Source="06-License-huA" SourceLine="2" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="59" Source="06-License-huA" SourceLine="2" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2017/5/15 - 14:39:50" eTime="2017/5/15 - 14:39:51" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="56" >
<Disp><![CDATA[06-License-huA Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T33">
<AName><![CDATA[07-PayModel-AllPay]]></AName>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:51]]></Time>
<TimeTick>1494830391</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:51]]></Time>
<TimeTick>1494830391</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[购车方式-全款购车.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:51]]></Time>
<TimeTick>1494830391</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="68" Source="07-PayModel-AllPay" SourceLine="2" >
<Disp><![CDATA[购车方式-全款购车.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="67" Source="07-PayModel-AllPay" SourceLine="2" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="66" Source="07-PayModel-AllPay" SourceLine="2" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2017/5/15 - 14:39:51" eTime="2017/5/15 - 14:39:52" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="63" >
<Disp><![CDATA[07-PayModel-AllPay Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T37">
<AName><![CDATA[08-PurchaseTime-m3Month]]></AName>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:52]]></Time>
<TimeTick>1494830392</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:52]]></Time>
<TimeTick>1494830392</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[购车时间-3个月以后.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:52]]></Time>
<TimeTick>1494830392</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="75" Source="08-PurchaseTime-m3Month" SourceLine="2" >
<Disp><![CDATA[购车时间-3个月以后.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="74" Source="08-PurchaseTime-m3Month" SourceLine="2" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="73" Source="08-PurchaseTime-m3Month" SourceLine="2" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2017/5/15 - 14:39:52" eTime="2017/5/15 - 14:39:53" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="70" >
<Disp><![CDATA[08-PurchaseTime-m3Month Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T41">
<AName><![CDATA[09-Area]]></AName>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:54]]></Time>
<TimeTick>1494830394</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:54]]></Time>
<TimeTick>1494830394</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[区域-浦东.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:54]]></Time>
<TimeTick>1494830394</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="82" Source="09-Area" SourceLine="2" >
<Disp><![CDATA[区域-浦东.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[商圈-金桥.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:55]]></Time>
<TimeTick>1494830395</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="85" Source="09-Area" SourceLine="4" >
<Disp><![CDATA[商圈-金桥.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="81" Source="09-Area" SourceLine="2" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="80" Source="09-Area" SourceLine="2" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2017/5/15 - 14:39:54" eTime="2017/5/15 - 14:39:56" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="77" >
<Disp><![CDATA[09-Area Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T46">
<AName><![CDATA[10-Trad-Step9]]></AName>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:57]]></Time>
<TimeTick>1494830397</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:57]]></Time>
<TimeTick>1494830397</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[最后的一个下一步.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:57]]></Time>
<TimeTick>1494830397</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="92" Source="10-Trad-Step9" SourceLine="3" >
<Disp><![CDATA[最后的一个下一步.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="91" Source="10-Trad-Step9" SourceLine="3" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="90" Source="10-Trad-Step9" SourceLine="3" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2017/5/15 - 14:39:56" eTime="2017/5/15 - 14:39:57" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="87" >
<Disp><![CDATA[10-Trad-Step9 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T50">
<AName><![CDATA[11-RegisterLogin]]></AName>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:59]]></Time>
<TimeTick>1494830399</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:59]]></Time>
<TimeTick>1494830399</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[用户手机号码.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/5/15 - 14:39:59]]></Time>
<TimeTick>1494830399</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="99" Source="11-RegisterLogin" SourceLine="3" >
<Disp><![CDATA[用户手机号码.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[老用户提示语.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2017/5/15 - 14:40:05]]></Time>
<TimeTick>1494830405</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="136" Source="11-RegisterLogin" SourceLine="24" >
<Disp><![CDATA[老用户提示语.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[获取验证码.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/5/15 - 14:40:06]]></Time>
<TimeTick>1494830406</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="140" Source="11-RegisterLogin" SourceLine="52" >
<Disp><![CDATA[获取验证码.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="98" Source="11-RegisterLogin" SourceLine="3" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="97" Source="11-RegisterLogin" SourceLine="3" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Action rID="T56">
<AName><![CDATA[12-AdminLogin]]></AName>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2017/5/15 - 14:40:08]]></Time>
<TimeTick>1494830408</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "IExplore.exe",1]]></Details>
<Time><![CDATA[2017/5/15 - 14:40:08]]></Time>
<TimeTick>1494830408</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="145" status="Passed" Source="12-AdminLogin" SourceLine="3" >
<Disp><![CDATA[Run "IExplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="144" status="Passed" Source="12-AdminLogin" SourceLine="3" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2017/5/15 - 14:40:10]]></Time>
<TimeTick>1494830410</TimeTick>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA["管理后台系统界面"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (2 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=管理后台系统界面<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>title=管理后台系统界面<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>openurl=res://ieframe.dll/securityatrisk.htm<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=安全设置风险<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hasstatusbar=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hasmenubar=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hastoolbar=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2017/5/15 - 14:40:10]]></Time>
<TimeTick>1494830410</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="148" Source="12-AdminLogin" SourceLine="6" >
<Disp><![CDATA["管理后台系统界面"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/5/15 - 14:40:10]]></Time>
<TimeTick>1494830410</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/5/15 - 14:40:10]]></Time>
<TimeTick>1494830410</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="151" Source="12-AdminLogin" SourceLine="6" >
<Disp><![CDATA[管理后台系统界面.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[用户名输入框.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[2017/5/15 - 14:40:13]]></Time>
<TimeTick>1494830413</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="154" Source="12-AdminLogin" SourceLine="8" >
<Disp><![CDATA[用户名输入框.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="150" Source="12-AdminLogin" SourceLine="6" >
<Disp><![CDATA[管理后台系统界面]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="147" Source="12-AdminLogin" SourceLine="6" >
<Disp><![CDATA[管理后台系统界面]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2017/5/15 - 14:40:13]]></Time>
<TimeTick>1494830413</TimeTick>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA["管理后台系统界面_2"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (2 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=管理后台系统界面<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>title=管理后台系统界面<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>openurl=http://oms-test.haomaiche.com/admin/login.html<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=管理后台系统界面<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hasstatusbar=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hasmenubar=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hastoolbar=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2017/5/15 - 14:40:13]]></Time>
<TimeTick>1494830413</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="157" Source="12-AdminLogin" SourceLine="11" >
<Disp><![CDATA["管理后台系统界面_2"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/5/15 - 14:40:13]]></Time>
<TimeTick>1494830413</TimeTick>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[userPassword.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Hmc1234"]]></Details>
<Time><![CDATA[2017/5/15 - 14:40:13]]></Time>
<TimeTick>1494830413</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="160" Source="12-AdminLogin" SourceLine="11" >
<Disp><![CDATA[userPassword.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/5/15 - 14:40:13]]></Time>
<TimeTick>1494830413</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="163" Source="12-AdminLogin" SourceLine="14" >
<Disp><![CDATA[login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="159" Source="12-AdminLogin" SourceLine="11" >
<Disp><![CDATA[管理后台系统界面]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="156" Source="12-AdminLogin" SourceLine="11" >
<Disp><![CDATA[管理后台系统界面_2]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2017/5/15 - 14:40:08" eTime="2017/5/15 - 14:40:13" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="141" status="Passed" >
<Disp><![CDATA[12-AdminLogin Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T69">
<AName><![CDATA[13-VerifyCode]]></AName>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[管理后台系统界面]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2017/5/15 - 14:40:16]]></Time>
<TimeTick>1494830416</TimeTick>
<Step rID="T71">