<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="VICTOR-PC"><DocLocation><![CDATA[C:\Unified Functional Testing\4.0\1117-HMC-H5-比价-模块化]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[1117-HMC-H5-比价-模块化]]></DName>
<Res><![CDATA[Res26]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[00-MainAction]]></AName>
<Action rID="T5">
<AName><![CDATA[01-HomeAction]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2017/3/27 - 17:53:15]]></Time>
<TimeTick>1490608395</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "chrome.exe",1]]></Details>
<Time><![CDATA[2017/3/27 - 17:53:15]]></Time>
<TimeTick>1490608395</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" Source="01-HomeAction" SourceLine="5" >
<Disp><![CDATA[Run "chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="01-HomeAction" SourceLine="5" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2017/3/27 - 17:53:18]]></Time>
<TimeTick>1490608398</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[好买车-首页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/3/27 - 17:53:18]]></Time>
<TimeTick>1490608398</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[好买车-首页.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/3/27 - 17:53:18]]></Time>
<TimeTick>1490608398</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" Source="01-HomeAction" SourceLine="8" >
<Disp><![CDATA[好买车-首页.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[选择车型按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/3/27 - 17:53:19]]></Time>
<TimeTick>1490608399</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" Source="01-HomeAction" SourceLine="10" >
<Disp><![CDATA[选择车型按钮.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="16" Source="01-HomeAction" SourceLine="8" >
<Disp><![CDATA[好买车-首页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" Source="01-HomeAction" SourceLine="8" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2017/3/27 - 17:53:14" eTime="2017/3/27 - 17:53:19" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Passed" >
<Disp><![CDATA[01-HomeAction Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T12">
<AName><![CDATA[02-CarBrand-Landrover]]></AName>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2017/3/27 - 17:53:21]]></Time>
<TimeTick>1490608401</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[好买车-首页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/3/27 - 17:53:21]]></Time>
<TimeTick>1490608401</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[路虎图标.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/3/27 - 17:53:21]]></Time>
<TimeTick>1490608401</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="27" Source="02-CarBrand-Landrover" SourceLine="3" >
<Disp><![CDATA[路虎图标.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[揽胜.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/3/27 - 17:53:22]]></Time>
<TimeTick>1490608402</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="30" Source="02-CarBrand-Landrover" SourceLine="5" >
<Disp><![CDATA[揽胜.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="26" Source="02-CarBrand-Landrover" SourceLine="3" >
<Disp><![CDATA[好买车-首页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="25" Source="02-CarBrand-Landrover" SourceLine="3" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2017/3/27 - 17:53:20" eTime="2017/3/27 - 17:53:22" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="22" >
<Disp><![CDATA[02-CarBrand-Landrover Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T17">
<AName><![CDATA[03-Trad-Step1]]></AName>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[好买车]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2017/3/27 - 17:53:23]]></Time>
<TimeTick>1490608403</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[车型详情页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2017/3/27 - 17:53:23]]></Time>
<TimeTick>1490608403</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[车型详情页.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/3/27 - 17:53:23]]></Time>
<TimeTick>1490608403</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="37" Source="03-Trad-Step1" SourceLine="3" >
<Disp><![CDATA[车型详情页.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA["去比价按钮"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2017/3/27 - 17:53:45]]></Time>
<TimeTick>1490608425</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="76" status="Warning" Source="03-Trad-Step1" SourceLine="5" >
<Disp><![CDATA["去比价按钮"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA["去比价按钮"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>type=submit<br>name=去比价 &gt<br>micclass=WebButton<br>html tag=BUTTON<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (3 objects found)&nbsp;</FONT></u><br>
micclass=WebButton<br>html tag=BUTTON<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=去比价 &gt<SPAN class=Failed> (Skipped)</SPAN><br>type=submit<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>html id=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>value=去比价 &gt<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>class=compare_price_popup<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2017/3/27 - 17:53:45]]></Time>
<TimeTick>1490608425</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="77" Source="03-Trad-Step1" SourceLine="5" >
<Disp><![CDATA["去比价按钮"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[去比价按钮.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2017/3/27 - 17:53:45]]></Time>
<TimeTick>1490608425</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="78" Source="03-Trad-Step1" SourceLine="5" >
<Disp><![CDATA[去比价按钮.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[第一步和最后一步的下一步]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "第一步和最后一步的下一步" (of class WebElement). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[2017/3/27 - 17:54:07]]></Time>
<TimeTick>1490608447</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[第一步和最后一步的下一步]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebElement<br>Html Tag = DIV<br>_xpath = //DIV/DIV/DIV/DIV/DIV/DIV[normalize-space()="下一步&gt"]<br>|Visible = -1<br>innertext = 下一步&gt<br>Html Id = <br>DHTML Class = next_step<br>]]></Details>
<Time><![CDATA[2017/3/27 - 17:54:07]]></Time>
<TimeTick>1490608447</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="119" status="Warning" nType="Description" Source="03-Trad-Step1" SourceLine="7" >
<Disp><![CDATA[第一步和最后一步的下一步]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="118" status="Failed" nType="Run Error" Source="03-Trad-Step1" SourceLine="7" >
<Disp><![CDATA[第一步和最后一步的下一步]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="36" status="Failed" Source="03-Trad-Step1" SourceLine="3" >
<Disp><![CDATA[车型详情页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="35" status="Failed" Source="03-Trad-Step1" SourceLine="3" >
<Disp><![CDATA[好买车]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;第一步和最后一步的下一步&quot; (of class WebElement). Verify that this object's properties match an object currently displayed in your application.<BR>Line (8): &quot;Browser(&quot;好买车&quot;).Page(&quot;车型详情页&quot;).WebElement(&quot;第一步和最后一步的下一步&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[2017/3/27 - 17:54:07]]></Time>
<TimeTick>1490608447</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="120" status="Failed" Source="03-Trad-Step1" SourceLine="7" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2017/3/27 - 17:54:10]]></Time>
<TimeTick>1490608450</TimeTick>
<NodeArgs eType="General" icon="13" nRep="121" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2017/3/27 - 17:53:22" eTime="2017/3/27 - 17:54:10" passed="0" failed="2" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="32" status="Failed" >
<Disp><![CDATA[03-Trad-Step1 Summary]]></Disp>
</NodeArgs>
</Action>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2017/3/27 - 17:54:10]]></Time>
<TimeTick>1490608450</TimeTick>
<NodeArgs eType="General" icon="13" nRep="123" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2017/3/27 - 17:53:14" eTime="2017/3/27 - 17:54:10" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[00-MainAction Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[1117-HMC-H5-比价-模块化 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2017/3/27 - 17:53:13" eTime="2017/3/27 - 17:54:10" passed="1" failed="2" warnings="2" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test 1117-HMC-H5-比价-模块化 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>